name: Github Pages Deploy

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: npm install && npm run build
        env: # https://stackoverflow.com/questions/63445967/githubs-action-is-not-building-react-application
          CI: false

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build